### ISSUE TITLE
Thanks for using LiteLLM - any feedback? 

### ISSUE THREAD

**Issue by ishaan-jaff** [mindsdb/otto#1]
Hi team thanks for using LiteLLM i'm the maintainer. I noticed you had issues with it being verbose? This should be fixed now, we have pre commit checks for `print` statements. It should only output logs when `litellm.set_verbose=True`

**How can we make LiteLLM better for your use case?**

**Comment by torrmal** [comment]
oh man, thank you, this is awesome, so far, I like it allot!!!
